# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c343e825a810addc543e718aa692715"
application_url = "https://stationery-leaf-cdt-knitting.trycloudflare.com"
embedded = true
name = "arham-test-app"
handle = "arham-test-app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-for-customer-account-test.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shopify_payments_accounts,write_products"

[auth]
redirect_urls = [
  "https://stationery-leaf-cdt-knitting.trycloudflare.com/auth/callback",
  "https://stationery-leaf-cdt-knitting.trycloudflare.com/auth/shopify/callback",
  "https://stationery-leaf-cdt-knitting.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
